language: generic
sudo: required
services:
   - docker


before_install: 
   - docker build -t TESTME -f Dockerfile.dev .

script:
   - docker run -e CI=true ranjankol/docker-react npm run test -- --coverage